CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_app_user_role CHECK (role IN ('CLIENT', 'OPERATOR'))
);

CREATE TABLE IF NOT EXISTS account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    balance NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_account_owner FOREIGN KEY (owner_user_id) REFERENCES app_user (id),
    CONSTRAINT chk_account_balance CHECK (balance >= 0),
    CONSTRAINT chk_account_currency CHECK (currency IN ('KZT', 'USD', 'EUR'))
);

CREATE TABLE IF NOT EXISTS payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    owner_account_id BIGINT NOT NULL,
    receiver_user_id BIGINT NOT NULL,
    receiver_account_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL,
    description VARCHAR(255),
    flagged BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_payment_owner_user FOREIGN KEY (owner_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_payment_owner_account FOREIGN KEY (owner_account_id) REFERENCES account (id),
    CONSTRAINT fk_payment_receiver_user FOREIGN KEY (receiver_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_payment_receiver_account FOREIGN KEY (receiver_account_id) REFERENCES account (id),
    CONSTRAINT chk_payment_amount CHECK (amount > 0),
    CONSTRAINT chk_payment_currency CHECK (currency IN ('KZT', 'USD', 'EUR')),
    CONSTRAINT chk_payment_status CHECK (status IN ('CREATED', 'CONFIRMED', 'REJECTED', 'FLAGGED'))
);

CREATE TABLE IF NOT EXISTS fraud_flag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    risk_level VARCHAR(10) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    flagged_by BIGINT,
    manual BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fraud_payment FOREIGN KEY (payment_id) REFERENCES payment (id),
    CONSTRAINT fk_fraud_flagged_by FOREIGN KEY (flagged_by) REFERENCES app_user (id),
    CONSTRAINT chk_fraud_risk_level CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE TABLE IF NOT EXISTS audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(30) NOT NULL,
    actor_username VARCHAR(50) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id BIGINT,
    outcome VARCHAR(10) NOT NULL,
    metadata VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_audit_event_type CHECK (event_type IN (
        'USER_REGISTERED',
        'LOGIN_SUCCEEDED',
        'LOGIN_FAILED',
        'PAYMENT_CREATED',
        'PAYMENT_CONFIRMED',
        'PAYMENT_FLAGGED',
        'ACCESS_DENIED'
    )),
    CONSTRAINT chk_audit_outcome CHECK (outcome IN ('SUCCESS', 'FAILURE'))
);

CREATE INDEX IF NOT EXISTS idx_account_owner_user_id ON account (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_payment_owner_user_id ON payment (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_payment_created_at ON payment (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_fraud_flag_payment_id ON fraud_flag (payment_id);
CREATE INDEX IF NOT EXISTS idx_fraud_flag_created_at ON fraud_flag (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_event_created_at ON audit_event (created_at DESC);
