ALTER TABLE app_user ALTER COLUMN id RESTART WITH 100;
ALTER TABLE account ALTER COLUMN id RESTART WITH 2000;
ALTER TABLE payment ALTER COLUMN id RESTART WITH 3000;
ALTER TABLE fraud_flag ALTER COLUMN id RESTART WITH 4000;
ALTER TABLE audit_event ALTER COLUMN id RESTART WITH 5000;
